[package]
name = "cognitive-complex-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
complexity = "0.1"
syn = "1.0"
regex = "1.5"
